[package]
name = "abc169"
version = "0.1.0"
authors = ["Kazumasa Shimomura <shimomura_kazumasa@cyberagent.co.jp>"]
edition = "2018"

# dependencies added to new project
[dependencies]

[profile.release]
lto = true
panic = 'abort'
